### ISSUE TITLE
kernel panic

### ISSUE THREAD

**Issue by norbibi** [golemfactory/golem-gpu-live#10]
build from commit 6616bb51ca6e685a1c4fb03bd56b21410b501ddc doesn't boot correctly.
kernel panic at initramfs stage with error:
run-init: can't execute '/sbin/init': No such file or directory

**Comment by marmarek** [comment]
The host or the VM? There is still some remaining issue with VM (although not about missing init). But host should boot correctly. Is initramfs loaded at all?

**Comment by norbibi** [comment]
My host boot screen:
![1700322495758](https://github.com/fepitre/golem-gpu-live/assets/81962856/f8ee87e2-a978-46c6-be6e-669a52bb69b5)
Maybe it's because of the build host tools.
If you have already built and validated this version, perhaps you could put it on https://mirror.notset.fr/golem/ so that we can test it independently of the build.

**Comment by norbibi** [comment]
I close the issue, I must have made a handling error.
The image boots correctly.
Sorry for the inconvenience.
