### ISSUE TITLE
Screen freezing when configuring provider

### ISSUE THREAD

**Issue by stan7123** [golemfactory/golem-gpu-live#12]
I was configuring a provider and the screen froze (attached screen). That was effect of GPU being reconfigured.
As a User, I was unable to tell if the computer hanged or all is good. To check it I had to log in using SSH.

Can we add an additional information at the `... [INFO] Configure passthrough.` line: 
" Your screen might turn off or freeze. Check if your provider is visible on the network: https://stats.golem.network/network/providers/online" or log in using SSH.

![IMG20231121142521](https://github.com/fepitre/golem-gpu-live/assets/2510442/9db0e4cb-38c1-4145-bd52-7ccbd18cc358)

**Comment by fepitre** [comment]
Message added.
