### ISSUE TITLE
Running command with golemwz returns error

### ISSUE THREAD

**Issue by stan7123** [golemfactory/golem-gpu-live#17]
When provider is already running and we're trying to change some settings using `golemwz` it returns errors on different providers.
```
golem@golem-provider:~$ golemwz --glm-per-hour 0.5
mount: /mnt: /dev/nvme0n1p3 already mounted on /mnt.
2024-01-09 22:19:01,954 [ERROR] Wizard error: Failed to mount configuration partition: Command '['sudo', 'mount', '/dev/disk/by-partlabel/Golem\\x20conf\\x20storage', '/mnt']' returned non-zero exit status 32.
```

Is this a bug?
Is this utility suitable to alter options during service runtime?

**Comment by marmarek** [comment]
I don't think `golemwz` is supposed to be called on already running provider. It can be called when booted into "no autostart" mode.
For changing parameters of already running provider native golem tools may be used (and it may also require restarting golemsp service, I'm not sure about this).
