### ISSUE TITLE
Is yagna updated automatically?

### ISSUE THREAD

**Issue by stan7123** [golemfactory/golem-gpu-live#25]
Is there any process of yagna update when provider is already running?
If yes, when does this happen?

Is the newest yagna fetched during first wizard setup?

**Comment by marmarek** [comment]
From the provider point of view, updates are fetched automatically (check is done every day, or maybe even few times a day). I'm not sure if service is automatically restarted after the update, but doing so is responsibility of relevant deb "postinst" script (yagna in this case).
From the maintainer point of view, pushing updates is described at https://github.com/golemfactory/golem-gpu-live?tab=readme-ov-file#setting-up-updates-repository
