### ISSUE TITLE
How to update ubuntu?

### ISSUE THREAD

**Issue by stan7123** [golemfactory/golem-gpu-live#27]
What does it take to update Ubuntu version or kernel version?

**Comment by marmarek** [comment]
Standard update within given Ubuntu version are applied automatically, this includes host kernel. Generating new live image will take latest packages at that time. The VM kernel + provider are covered in https://github.com/golemfactory/golem-gpu-live?tab=readme-ov-file#setting-up-updates-repository.
As for switching to newer Ubuntu version, search this and the golem-nvidia-kernel repository for `jammy` and replace with appropriate code name of newer version. Some fixups might be needed after that. Already running providers will not automatically update to newer Ubuntu version this way, they need to download new live image.
