### ISSUE TITLE
Additional dialog screen during setup - node name

### ISSUE THREAD

**Issue by stan7123** [golemfactory/golem-gpu-live#28]
Because users might not notice their node's generated name during setup (displayed only at the end for a short while), they have to log in on the provider to check it. 
We would like them to be able to configure it by themselves as one of the steps in wizard.

What needs to be done to add another screen for this purpose and how to inject this into yagna?  Is it only wizard development + passing to yagna config, or does that require something more?
We would like to be able to provide this information in first boot configuration file.

**Comment by nieznanysprawiciel** [comment]
`golemsp settings set --node-name my-awsome-name`

**Comment by marmarek** [comment]
It should be enough to add in `rootfs/golemwz.py` relevant handling. There are a few things to add in that script, take a look for example at `glm_account` handling.
