### ISSUE TITLE
Problem when selecting persistent storage partition to other than default

### ISSUE THREAD

**Issue by stan7123** [golemfactory/golem-gpu-live#3]
When I selected nvme partition as storage, the wizard stopped working and I was presented with command line prompt without any message.

It looks like the storage was mounted but there was a problem with permissions.
![storage-set-to-nvme-partition](https://github.com/fepitre/golem-gpu-live/assets/2510442/b30a89ad-8bff-4a09-98dc-91c882b43305)

Additionally, after getting into terminal when error occurred I would expect to:
- have some kind of message what went wrong
- command(s) to check the logs (what went wrong or the details of what went wrong)
- URL to somewhere where user can find an instruction/wiki/FAQ

**Comment by stan7123** [comment]
Is this issue being worked on?
Is it possible to reproduce?

**Comment by marmarek** [comment]
This looks like a documentation issue. The custom partition is mounted as-is, and expected to be writable by the "golem" user (UID 1000). We have considered automatic chown, but it's a massive footgun (if you select partition with some existing data on it, running chown on it may be catastrophic, for example if that was a home dir of another Linux).

**Comment by marmarek** [comment]
I have an idea: use not a root directory of the partition, but a subdirectory (`golem-live`?). Then, it should be relatively safe to change permissions of that directory automatically, even on pre-existing partition.

**Comment by fepitre** [comment]
Done as proposed.
