### ISSUE TITLE
Block system stdout to appear in the wizard

### ISSUE THREAD

**Issue by stan7123** [golemfactory/golem-gpu-live#30]
One of the users got system message when inside the wizard.
![image](https://github.com/golemfactory/golem-gpu-live/assets/2510442/eaba890c-ca78-4eca-90b3-5e458c0b17bd)

Is it possible to block showing such messages during configuration?

**Comment by marmarek** [comment]
It should be possible by adding `dmesg -n 0` call before starting the wizard (`ExecStartPre=+/usr/bin/dmesg -n 0` in the systemd unit?)
