### ISSUE TITLE
Problem with setting up a provider

### ISSUE THREAD

**Issue by stan7123** [golemfactory/golem-gpu-live#9]
I was trying to set up two computers from the same exact image -> https://mirror.notset.fr/golem/golem-gpu-live-231019T120338Z.img.xz

I went through the wizard and got thrown into console.
I checked `golemwz.log` and it shows an error
`Unexpected error: '0403'`

The computers' base is rather old (5th Intel generation) but with 3060 and 3090 cards. The behavior on both was the same.

![IMG20231117115929](https://github.com/fepitre/golem-gpu-live/assets/2510442/8a9530d4-d4da-4002-bba3-b6984878e16b)

![IMG20231117125951](https://github.com/fepitre/golem-gpu-live/assets/2510442/a0b6cacd-59aa-4db3-a8e5-d99e2d11def0)

**Comment by marmarek** [comment]
This looks to be the same issue as #7, we have this fixed in git already, new image for testing will be delivered in 1-2h.

**Comment by stan7123** [comment]
There's no such error anymore with new image :tada:
